#image: alpine:latest
image: node:latest

#build:
  
pages:
  stage: deploy
  before_script:
    - npm install
  cache:
    paths:
      - node_modules/
  script:
    npm run build
  artifacts:
    paths:
    - public
  only:
  - master
